targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/src/_generated/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/src/_generated/{{}}.freezed.dart'
      json_serializable:
        options:
          # オブジェクトを含んだFreezedクラスをJSONに変換する
          explicit_to_json: true
          # JSONオブジェクトのキーをSnakeCaseに変換する
          field_rename: snake  