name: yumemi_flutter_test
description: "Flutter Test For Yumemi Corporation"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1
  http: ^1.2.2
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.3.3
  flutter_markdown: ^0.7.4
  collection: any
  lottie: ^3.3.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter  
  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3
  mockito: ^5.4.4
  faker: ^2.2.0
  flutter_gen_runner: ^5.8.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/svg/
    - assets/lottie/

# FlutterGenの設定
flutter_gen:
  output: lib/src/_generated/gen/
  lineLength: 80

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
